# This is a basic workflow to help you get started with Actions
name: Integration Release

on:
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout meta repo
        uses: actions/checkout@v4

      - name: Fetch Subprojects
        run: bash fetch.sh

        
      - name: Fetch subproejcts into mera repo
        env:
          GH_TOKEN: ${{ secrets.ORG_READ_TOKEN }}
        run: bash fetch.sh
        
      - name: Package integrated bundle
        run: |
          tar czf Porject-${{ github.ref_name }}.tar.gz lattices
          
      - name: Create GitHub Release + upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: Porject-${{ github.ref_name }}.tar.gz
