# This is a basic workflow to help you get started with Actions
name: Integration Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v1.2.0)"
        required: true
        type: string

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout meta repo
        uses: actions/checkout@v4

      - name: Set release name
        run: |
          echo "RELEASE_NAME=Project-${{ inputs.version }}" >> $GITHUB_ENV

      - name: Build lattice directory
        run: |
          PDIR=$RELEASE_NAME/lattices
          mkdir $PDIR
          mkdir -p $RELEASE_NAME/lattices
          git clone https://github.com/ykkan/Project_A.git $PDIR/Project_A
          git clone https://github.com/ykkan/Project_B.git $PDIR/Project_B

      - name: Package integrated bundle
        run: |
          tar czf $RELEASE_NAME.tar.gz lattices
          
      - name: Create GitHub Release + upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          files: $RELEASE_NAME.tar.gz



          
